In [9]:
import pandas as pd
import numpy as np
import random 
import datetime

In [2]:
#Inputs
s = 50 #size of the grid
N = 100 #size of population
M = round(N * 0.07) #Number of infectious population
Et = 2 #Number of days staying exposed
It = 21 #Number of days staying infectious
Mt = 2 #Number of daily movements
D = 30 #Number of days
death_rate = 100
expose_rate = 3

In [3]:
#Initialization
S = N - M #Susceptible population
E = 0 #Exposed population
I = M #Number of infectious population 
R = 0 #Recovered population
P = S + E + I + R #Total population
Economy = 0 #Daily economic transaction
Cum_Economy = 0 #Total economic transaction

In [4]:

infectious_array[0][0]

NameError: name 'infectious_array' is not defined

In [5]:
dummy_array = np.zeros(shape=(P,8))
df = pd.DataFrame(dummy_array,columns=['x','y','Day','Susceptible','Exposed','Infectious','Recovered','GG'])
df = df.astype({'x':int,'y':int,'Day':int,'Susceptible':bool,'Exposed':int,'Infectious':int,'Recovered':bool,'GG':bool})
df['Susceptible'] = True
infectious_array = np.zeros(shape=(s+1,s+1), dtype=bool)
#Appending infectious population in 
dfupdate=df.sample(M)
dfupdate['Infectious'] = np.random.randint(1,It, size=len(dfupdate))
dfupdate['Susceptible'] = False
df.update(dfupdate)
update_list = dfupdate.index.tolist() 
#Dispersing people randomly among grid
df['x'] = np.random.randint(0,s, size=len(df))
df['y'] = np.random.randint(0,s, size=len(df))
df

     x   y  Day Susceptible  Exposed  Infectious Recovered     GG
0   37  38  0.0        True      0.0         0.0     False  False
1   21   3  0.0        True      0.0         0.0     False  False
2   41  22  0.0       False      0.0        18.0     False  False
3   27   1  0.0        True      0.0         0.0     False  False
4   26  42  0.0        True      0.0         0.0     False  False
..  ..  ..  ...         ...      ...         ...       ...    ...
95  46  24  0.0        True      0.0         0.0     False  False
96  25  20  0.0        True      0.0         0.0     False  False
97  35  44  0.0        True      0.0         0.0     False  False
98   6  20  0.0        True      0.0         0.0     False  False
99   9  44  0.0        True      0.0         0.0     False  False

[100 rows x 8 columns]

In [6]:
KPIs = ['Active Cases','Newly Infected','Cured Cases','Death Cases','Reproduction Rate','Economy','Current Movement Restriction']
KPI_df = pd.DataFrame(columns=KPIs)
KPI_df = KPI_df.fillna(0)
KPI_df.loc[0,'Active Cases'] = I     
KPI_df.loc[0,'Newly Infected'] = df.loc[df['Infectious'] == 1].Infectious.count()
KPI_df.loc[0,'Cured Cases'] = 0
KPI_df.loc[0,'Death Cases'] = 0
KPI_df.loc[0,'Reproduction Rate'] = df.loc[df['Infectious'] == 1].Infectious.count()
KPI_df.loc[0,'Economy'] = Economy
KPI_df.loc[0,'Current Movement Restriction'] = 0

In [7]:
np.sum(infectious_array)

0

In [263]:
KPI_df

,Active Cases,Newly Infected,Cured Cases,Death Cases,Reproduction Rate,Economy,Current Movement Restriction
0,1,0,0,0,0,0,0

In [10]:
#['x','y','Day','Susceptible','Exposed','Infectious','Recovered','GG']
cured_num = 0
dead_num = 0
active_num = I
start = datetime.datetime.now()
for day in range(D):    
    newly_infected = 0
    Economy = 0 #Economy per day
    for mt in range(Mt):
        for p in range(P):
            if df.loc[p,'GG'] == False: #If the person is not dead
                new_move_x = random.choice(range(-1,2))
                new_move_y = random.choice(range(-1,2))
                prev_x = df.loc[p,'x']
                prev_y = df.loc[p,'y']
                df.loc[p,'x'] = max(min(df.loc[p,'x']+new_move_x,s),0) #make valid movements in the grid
                df.loc[p,'y'] = max(min(df.loc[p,'y']+new_move_y,s),0)
                df.loc[p,'Day'] = day + 1 #updating the day counter                
                
                if (df.loc[p,'Infectious'] > 0) and (df.loc[p,'Recovered'] == False): #If a person is in infectious state
                    if df.loc[p,'Infectious'] - random.choice(range(0,7)) >= It: #If the infectious days are completed
                        if random.choice(range(0,death_rate)) > (death_rate-2): #If the person dies(with probability distribution 1:4)                           
                            df.loc[p,'Infectious'] = 0
                            df.loc[p,'GG'] = True #Kill the person
                            infectious_array[prev_x][prev_y] = False
                            print(f"Dead and + {infectious_array[df.loc[p,'x']][df.loc[p,'y']]}")
                            dead_num = dead_num+1   
                            active_num = active_num-1
                        else: #If the person survives
                            df.loc[p,'Infectious'] = 0
                            df.loc[p,'Recovered'] = True #Recover the person
                            infectious_array[prev_x][prev_y] = False
                            cured_num = cured_num+1
                            active_num = active_num-1
                    elif mt+1 == Mt:
                        df.loc[p,'Infectious'] = df.loc[p,'Infectious'] + 1 #Increase the infectious day counter
                        infectious_array[df.loc[p,'x']][df.loc[p,'y']] = True
                        infectious_array[prev_x][prev_y] = False
                elif (df.loc[p,'Exposed'] > 0) and (df.loc[p,'Infectious'] == 0): #If a person is in exposed state 
                    print(f"Exposed {infectious_array[prev_x][prev_y]}")
                    if (df.loc[p,'Exposed'] - random.choice(range(0,2))) >= Et: #If the person has reached the exposed day limit?  7
                        df.loc[p,'Exposed'] = 0
                        df.loc[p,'Infectious'] = 1 #Increase the infectious day counter, now the person is infectious
                        infectious_array[df.loc[p,'x']][df.loc[p,'y']] = True
                        infectious_array[prev_x][prev_y] = False
                        active_num = active_num+1
                        newly_infected = newly_infected+1
                        print(f"Became infected {infectious_array[df.loc[p,'x']][df.loc[p,'y']]}")
                    elif mt+1 == Mt:
                        df.loc[p,'Exposed'] = df.loc[p,'Exposed'] + 1 #Increase the exposed day counter
                        
                elif df.loc[p,'Susceptible'] == True: #If the person is in susceptible state 
                    if ((infectious_array[df.loc[p,'x']][df.loc[p,'y']])|(infectious_array[max(df.loc[p,'x']-1,0)][df.loc[p,'y']])|(infectious_array[max(df.loc[p,'x']-1,0)][max(df.loc[p,'y']-1,0)])|(infectious_array[df.loc[p,'x']][max(df.loc[p,'x']-1,0)])|(infectious_array[min(df.loc[p,'x']+1,s)][df.loc[p,'y']])|(infectious_array[df.loc[p,'x']][min(df.loc[p,'y']+1,s)])|(infectious_array[min(df.loc[p,'x']+1,s)][min(df.loc[p,'y']+1,s)])|(infectious_array[max(df.loc[p,'x']-1,0)][min(df.loc[p,'y']+1,s)])|(infectious_array[min(df.loc[p,'x']+1,s)][max(df.loc[p,'y']-1,0)])):
                    
                    
                        if random.choice(range(0,expose_rate)) > (expose_rate-2):
                            df.loc[p,'Exposed'] = 1
                            df.loc[p,'Susceptible'] = False
                if df.loc[p,'Infectious'] == 0:
                    Cum_Economy = Cum_Economy + round(random.uniform(0.8,1), 2)
                    Economy = Economy + round(random.uniform(0.8,1), 2)
                
    #Gathering the data
    KPI_df.loc[day + 1,'Active Cases'] = active_num
    KPI_df.loc[day + 1,'Newly Infected'] = newly_infected
    KPI_df.loc[day + 1,'Cured Cases'] = cured_num
    KPI_df.loc[day + 1,'Death Cases'] = dead_num
    KPI_df.loc[day + 1,'Reproduction Rate'] = active_num
    KPI_df.loc[day + 1,'Economy'] = Economy
    KPI_df.loc[day + 1,'Current Movement Restriction'] = 0

    
end = datetime.datetime.now()
print("day: ", day, " took this time", end - start)

Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected False
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected False
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Became infected True
Exposed True
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed True
Exposed False
Exposed False
Exposed False
Became infected False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Became infected True
Exposed True
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Exposed True
Became infected True
Exposed True
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed True
Became infected True
Exposed False
Exposed False
Exposed False
Exposed True
Exposed False
Exposed True
Exposed False
Became infected True
Exposed True
Exposed False
Became infected True
Exposed True
Became infected True
Exposed False
Exposed False
Became infected True
Exposed False
Exposed True
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed True
Exposed False
Became infected True
Exposed True
Became infected True
Exposed True
Exposed False
Exposed True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Became infected False
Exposed False
Became infected True
Exposed True
Exposed False
Became infected True
Exposed False
Exposed True
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected False
Exposed True
Became infected True
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Exposed True
Became infected True
Exposed True
Exposed True
Exposed False
Exposed True
Became infected True
Exposed True
Exposed False
Exposed False
Became infected True
Exposed False
Exposed True
Exposed False
Exposed False
Exposed False
Became infected True
Exposed False
Exposed True
Exposed False
Exposed True
Exposed False
Exposed True
Exposed False
Exposed False
Became infected True
Exposed False
Became infected False
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed True
Exposed False
Became infected True
Exposed True
Became infected True
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Became infected True
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Exposed False
Became infected True
Exposed True
Exposed False
Exposed False
Became infected False
Exposed False
Became infected True
Exposed False
Became infected False
Dead and + False
Exposed False
Exposed False
Exposed True
Exposed False
Exposed True
Exposed False
Exposed False
Became infected True
Exposed True
Exposed True
Became infected True
Exposed False
Became infected True
Exposed True
Exposed True
Became infected True
day:  29  took this time 0:00:20.666163

In [265]:
df

     x   y   Day Susceptible  Exposed  Infectious Recovered     GG
0   19  25  30.0       False      0.0        23.0     False  False
1   22  17  30.0       False      0.0         0.0      True  False
2   21   6  30.0       False      0.0         0.0      True  False
3    1   4  30.0        True      0.0         0.0     False  False
4   14   9  30.0       False      0.0         8.0     False  False
..  ..  ..   ...         ...      ...         ...       ...    ...
95  10  23  30.0       False      0.0        10.0     False  False
96  11   7  30.0       False      0.0        11.0     False  False
97   8  15  30.0       False      0.0        12.0     False  False
98   0  17  30.0        True      0.0         0.0     False  False
99  14  15  30.0       False      0.0         8.0     False  False

[100 rows x 8 columns]

In [266]:
KPI_df

,Active Cases,Newly Infected,Cured Cases,Death Cases,Reproduction Rate,Economy,Current Movement Restriction
0,1,0,0,0,0,0,0
1,1,0,0,0,1,178.83,0
2,1,0,0,0,1,178.2,0
3,2,1,0,0,2,177.62,0
4,3,1,0,0,3,174.39,0
5,4,1,0,0,4,173.28,0
6,5,1,0,0,5,172.33,0
7,6,1,0,0,6,168.46,0
8,8,2,0,0,8,166.33,0
9,14,6,0,0,14,153.99,0
10,15,1,0,0,15,153.61,0
11,19,4,0,0,19,145.87,0
12,23,4,0,0,23,140.17,0
13,25,2,0,0,25,134.22,0
14,28,3,0,0,28,129.51,0
15,31,3,0,0,31,125.44,0
16,35,4,0,0,35,116.65,0
17,39,4,0,0,39,110.21,0
18,42,3,0,0,42,104.28,0
19,47,6,1,0,47,97.94,0
20,50,3,1,0,50,91.43,0
21,58,8,1,0,58,79.28,0
22,63,5,1,0,63,66.7,0
23,67,4,1,0,67,60,0
24,71,4,1,0,71,52.56,0
25,73,2,1,0,73,48.38,0
26,70,1,5,0,70,53.51,0
27,75,5,5,0,75,44.94,0
28,74,2,8,0,74,44.45,0
29,74,2,10,0,74,48.58,0
30,73,1,12,0,73,49.29,0

In [269]:
np.sum(infectious_array[15])

9

In [270]:
infectious_array[10]

array([ True, False, False, False,  True, False, False,  True,  True,
       False, False, False, False,  True, False, False,  True,  True,
        True, False,  True, False,  True,  True,  True, False])

In [208]:
df

       x    y   Day Susceptible  Exposed  Infectious Recovered     GG
0    185   22  30.0        True      0.0         0.0     False  False
1     36  157  30.0        True      0.0         0.0     False  False
2    170  194  30.0        True      0.0         0.0     False  False
3    162  141  30.0        True      0.0         0.0     False  False
4    229   74  30.0        True      0.0         0.0     False  False
..   ...  ...   ...         ...      ...         ...       ...    ...
995   31   43  30.0        True      0.0         0.0     False  False
996   20   35  30.0        True      0.0         0.0     False  False
997   15  134  30.0       False      0.0         8.0     False  False
998  107   90  30.0        True      0.0         0.0     False  False
999  107   45  30.0        True      0.0         0.0     False  False

[1000 rows x 8 columns]